### ISSUE TITLE
Unknown Error - 502 status code from client

### ISSUE THREAD

**Issue by SDanousis** [localtunnel/server#13]
I've read through issue #8  and I have realized that I am facing a similar problem even though I am using the lt syntax as per your instruction.
i.e. I am running the server at port 2530 by the following 
`DEBUG=localtunnel* ./server --port 2530`
and I run the client by the following
`lt --host "http://sub.example.org:2530" --port 2350 --subdomain testreq`
At the client end I've added a long stack traces lib (https://github.com/mattinsler/longjohn) and the error  I get there is the following:

```
Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/lib/node_modules/localtunnel/client.js:215:27)
    at self.callback (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:122:22)
    at EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:655:16)
    at EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:617:14)
    at EventEmitter.emit (events.js:117:20)
---------------------------------------------
    at Request.init (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:126:10)
    at new Request (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:105:8)
    at request (/usr/lib/node_modules/localtunnel/node_modules/request/main.js:968:11)
    at get_url (/usr/lib/node_modules/localtunnel/client.js:204:9)
    at Tunnel._init (/usr/lib/node_modules/localtunnel/client.js:232:7)
    at Tunnel.open (/usr/lib/node_modules/localtunnel/client.js:291:10)
    at localtunnel (/usr/lib/node_modules/localtunnel/client.js:320:12)
    at Object.<anonymous> (/usr/lib/node_modules/localtunnel/bin/client:40:1)
```

while, at the server, all I get is the following:

```
localtunnel server listening on port: 2530 +0ms
  localtunnel-server request /testreq +0ms
```

Any thoughts?

Update:
After changing the hostname and DNS settings by removing the subdomain(e.g. change _http://sub.example.com_ to _http://example.com_) I finally got it to work!

**Comment by code-guru** [comment]
The problem still exists when using browser-sync.
