### ISSUE TITLE
Leaking Sockets

### ISSUE THREAD

**Issue by a7medkamel** [localtunnel/server#43]
Looks like the server is leaking sockets.

My server gets 'clients' connecting to new subdomains frequently; the setup is probably similar to localtunnel.me with thousands of client connections over time.

After a while; my system refuses to allocate anymore sockets to the process.

I haven't found the leak yet;

> I made small modification to my fork; proxy.js:118:19 is 'client_server.listen'

---

error: listen EMFILE 0.0.0.0
    at Object.exports._errnoException (util.js:855:11)
    at exports._exceptionWithHostPort (util.js:878:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1328:5)
    at new Proxy (/home/nodejs/taskmill/cloud/www/node_modules/localtunnel-server/proxy.js:118:19)
    at Proxy (/home/nodejs/taskmill/cloud/www/node_modules/localtunnel-server/proxy.js:9:16)
    at new_client (/home/nodejs/taskmill/cloud/www/node_modules/localtunnel-server/server.js:169:18)
    at /home/nodejs/taskmill/cloud/www/node_modules/localtunnel-server/server.js:239:9
    at Layer.handle [as handle_request](/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/layer.js:95:5)
    at /home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:277:22
    at param (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:349:14)
    at param (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:410:3)
    at next (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request](/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:312:13)
    at /home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:271:10)
    at query (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request](/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:312:13)
    at /home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:330:12)
    at next (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/router/index.js:176:3)
    at EventEmitter.handle (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/application.js:173:10)
    at app (/home/nodejs/taskmill/cloud/www/node_modules/express/lib/express.js:38:9)
    at Server.<anonymous> (/home/nodejs/taskmill/cloud/www/node_modules/localtunnel-server/server.js:278:9)

**Comment by defunctzombie** [comment]
Are you running master or some previous version?

If you find the source of the issue please let me know! I suspect you are correct in that there might be a leak.

The version I run on localtunnel.me is different from current master; in master I have started to refactor some things and remove an old dependency bouncy hopefully leading to simpler code.

**Comment by a7medkamel** [comment]
I am running a fork but it is sync-ed with latest from master. I haven't had enough time to investigate yet; will let you know if I find something.

**Comment by a7medkamel** [comment]
#46 might be related

**Comment by defunctzombie** [comment]
Server has gone through a major overhaul recently; if this is still a problem please open a new ticket with steps to reproduce.
