### ISSUE TITLE
throw an error when connect to server

### ISSUE THREAD

**Issue by rongself** [localtunnel/server#44]
my ``` lt ``` version is 1.8.1,and node version is v0.10.41
localtunnel-server version is v0.8.0,and node version is v0.10.41
then
```shell
ubuntu@myserver:~/localtunnel-server/server$ ./bin/server --port 2333
  localtunnel server listening on port: 2333 +0ms
```
when i connect to the server

```shell
[www@localhost ~]$ lt --host http://tunnel.mydomain.com:2333 --port 8000

/home/www/.nvm/v0.11.8/lib/node_modules/localtunnel/bin/client:48
        throw err;
              ^
Error: localtunnel server returned an error, please try again
    at Request._callback (/home/www/.nvm/v0.11.8/lib/node_modules/localtunnel/lib/Tunnel.js:53:27)
    at Request.self.callback (/home/www/.nvm/v0.11.8/lib/node_modules/localtunnel/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:106:17)
    at Request.<anonymous> (/home/www/.nvm/v0.11.8/lib/node_modules/localtunnel/node_modules/request/request.js:1082:10)
    at Request.EventEmitter.emit (events.js:125:20)
    at IncomingMessage.<anonymous> (/home/www/.nvm/v0.11.8/lib/node_modules/localtunnel/node_modules/request/request.js:1009:12)
    at IncomingMessage.EventEmitter.emit (events.js:125:20)
    at _stream_readable.js:896:16
    at process._tickCallback (node.js:311:11)

```

and the server side output: 
```shell
  localtunnel-server request /?new +10s
```

anyone can help?

**Comment by rongself** [comment]
i found the reason,seems like this issue:[https://github.com/localtunnel/server/issues/31](https://github.com/localtunnel/server/issues/31)
