### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by kilbyjmichael** [localtunnel/server#52]
> bin/server --port 5000

/home/user/localtunnel-server/bin/server:36
server.listen(argv.port, () => {
                          ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by defunctzombie** [comment]
Your version of node is too old.
