### ISSUE TITLE
Setup Fail after npm install

### ISSUE THREAD

**Issue by foreseaz** [localtunnel/server#54]
Hi, I got the following error running `bin/server --port 1234` after `npm install`
```
server.listen(argv.port, () => {
                          ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at `node.js:902:3`
```

Does it related to `babel` runtime that could not resolve ES6? Could you please give some instructions to solve this? thanks a lot.

**Comment by defunctzombie** [comment]
Just a newer version of node. v6 should work
