### ISSUE TITLE
(111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by patrickml** [localtunnel/server#56]
We are trying to setup another server so that others can still use your great package. Im sure your servers are flooded. We were trying to teach a group of 75 students tonight at 5pm how to build bots, but the local tunnel servers can be spotty so we wanted to setup our own server.

We purchased a wildcard ssl cert and all is well, but for some reason we keep getting these errors from the server

```
root@localtunnel-1:/home/patrick# lt -h "https://bot-tunnel.com" -p 3000
/usr/local/lib/node_modules/localtunnel/bin/client:48
        throw err;
        ^

Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/local/lib/node_modules/localtunnel/lib/Tunnel.js:53:27)
    at Request.self.callback (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
root@localtunnel-1:/home/patrick# docker logs -f 62b574c59565
2016/12/15 16:11:55 [error] 5#5: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: "
http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:12:15 [error] 5#5: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: "
http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:12:34 [error] 5#5: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 104.131.9.173, server: , request: "HEAD / HTTP/1.1", upstream: "htt
p://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:13:22 [error] 5#5: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: "
http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:13:28 [error] 5#5: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: 
"http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:15:03 [error] 5#5: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 104.131.9.173, server: , request: "HEAD / HTTP/1.1", upstream: "ht
tp://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:16:46 [error] 5#5: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 104.131.9.173, server: , request: "HEAD / HTTP/1.1", upstream: "ht
tp://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:17:43 [error] 5#5: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 104.131.9.173, server: , request: "HEAD / HTTP/1.1", upstream: "ht
tp://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:17:59 [error] 5#5: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 193.111.60.5, server: , request: "GET / HTTP/2.0", upstream: "http
://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:17:59 [error] 5#5: *25 connect() failed (111: Connection refused) while connecting to upstream, client: 193.111.60.5, server: , request: "GET /favicon.ico HTTP/2.0", upst
ream: "http://127.0.0.1:3000/favicon.ico", host: "bot-tunnel.com"
2016/12/15 16:18:00 [error] 5#5: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 193.111.60.5, server: , request: "GET /favicon.ico HTTP/2.0", upst
ream: "http://127.0.0.1:3000/favicon.ico", host: "bot-tunnel.com"
2016/12/15 16:22:51 [error] 5#5: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 205.251.129.126, server: , request: "GET / HTTP/2.0", upstream: "h
ttp://127.0.0.1:3000/", host: "bot-tunnel.com"
2016/12/15 16:22:51 [error] 5#5: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 205.251.129.126, server: , request: "GET /favicon.ico HTTP/2.0", u
pstream: "http://127.0.0.1:3000/favicon.ico", host: "bot-tunnel.com"
2016/12/15 16:22:52 [error] 5#5: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 205.251.129.126, server: , request: "GET /favicon.ico HTTP/2.0", u
pstream: "http://127.0.0.1:3000/favicon.ico", host: "bot-tunnel.com"
2016/12/15 16:24:45 [error] 5#5: *34 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: 
"http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:27:04 [error] 5#5: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 76.99.69.216, server: , request: "GET / HTTP/2.0", upstream: "http
://127.0.0.1:3000/", host: "bot-tunnel.com", referrer: "https://support.namecheap.com/visitor/index.php?/LiveChat/Chat/Start"
2016/12/15 16:27:04 [error] 5#5: *36 connect() failed (111: Connection refused) while connecting to upstream, client: 76.99.69.216, server: , request: "GET /favicon.ico HTTP/2.0", upst
ream: "http://127.0.0.1:3000/favicon.ico", host: "bot-tunnel.com", referrer: "https://bot-tunnel.com/"
2016/12/15 16:30:07 [error] 5#5: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 104.197.143.216, server: , request: "GET /?new HTTP/1.1", upstream
: "http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
2016/12/15 16:30:13 [error] 5#5: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 104.197.143.216, server: , request: "GET /?new HTTP/1.1", upstream
: "http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
tion refused) while connecting to upstream, client: 104.197.143.216, server: , request: "GET /?new HTTP/1.1", upstream
: "http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
```

**Comment by defunctzombie** [comment]
```
2016/12/15 16:11:55 [error] 5#5: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 76.98.113.158, server: , request: "GET /?new HTTP/1.1", upstream: "
http://127.0.0.1:3000/?new", host: "bot-tunnel.com"
```

This means that the nginx proxy was not able to talk to the localtunnel server (which should be running in a container next to it) and listening on port 3000.
