### ISSUE TITLE
Crashing with connection refused when left idle

### ISSUE THREAD

**Issue by LividLick** [localtunnel/server#71]
I absolutely love localtunnel! That being said, I've been encountering an issue where the client will just die and produce an error stack when left idle for a little while. (I have not timed this, but it always happens)

I can connect to the --subdomain I set when launching it just fine though until it dies.

Node version: **8.6.0**
```javascript
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:41159 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

Is there something I can do to prevent this happening?  Sometimes I'll have to run LT on my office desktop/scotch-box when I'm out with clients showing them current progress and whatnot.

**Comment by LividLick** [comment]
Posted under the wrong repository, sorry!
